Name="github_webhook_action"

# date '+%Y-%m-%d_%H:%M:%S_%Z'
BuildTime="2024-06-04_11:01:17_KST"

[server]
Port=8080
# google appengine 은 /tmp 에만 쓰기할 수 있다.
# https://cloud.google.com/appengine/docs/standard/using-temp-files?tab=go
LogFile="/tmp/github_webhook_action.log"
LogLevel="info"
LogIsJsonFormat=false
WebhookSecretKey="ysoftman"

[[hook]]
RepoName="https://github.com/ysoftman/github_webhook_action"

[[hook]]
RepoName="https://github.com/ysoftman/test_code"

[[hook]]
RepoName="https://github.com/ysoftman/myenv"

[[hook]]
RepoName="https://github.com/ysoftman/ysoftman.github.io"

[action]
Enable=false
Method="post"
Auth=""
URL="https://httpbin.org/post"

