Name="github_webhook_action"

# date '+%Y-%m-%d_%H:%M:%S_%Z'
BuildTime="2024-06-03_23:35:20_KST"

[server]
Port=8080
LogLevel="info"
LogIsJsonFormat=false
WebhookSecretKey="ysoftman"

[[hook]]
RepoName="https://github.com/ysoftman/github_webhook_action"

[[hook]]
RepoName="https://github.com/ysoftman/test_code"

[[hook]]
RepoName="https://github.com/ysoftman/myenv"

[[hook]]
RepoName="https://github.com/ysoftman/ysoftman.github.io"

[action]
Enable=false
Method="post"
Auth=""
URL="https://httpbin.org/post"

