Name="github_webhook_action"

# date '+%Y-%m-%d_%H:%M:%S_%Z'
BuildTime="2024-04-07_21:06:32_KST"

[server]
Port=80
LogLevel="info"
LogIsJsonFormat=false
WebhookSecretKey="ysoftman"

[action.api]
Enable=false
Mothod="post"
Auth=""
URL="https://httpbin.org/post"

[[action.target]]
RepoName="https://github.com/ysoftman/github_webhook_action"
TargetID=1
RequestBody="""
{}
"""

[[action.target]]
RepoName="https://github.com/ysoftman/test_code"
TargetID=2
RequestBody="""
{}
"""
